/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Neighborhood = IDL.Variant({
  'Shinjuku' : IDL.Null,
  'Nihonbashi' : IDL.Null,
  'Ginza' : IDL.Null,
  'Aoyama' : IDL.Null,
  'TokyoStation' : IDL.Null,
  'Akasaka' : IDL.Null,
  'Asakusa' : IDL.Null,
  'Atago' : IDL.Null,
  'Shibuya' : IDL.Null,
  'Roppongi' : IDL.Null,
});
export const Mode = IDL.Variant({ 'Date' : IDL.Null, 'Business' : IDL.Null });
export const Category = IDL.Variant({
  'Bar' : IDL.Null,
  'Sushi' : IDL.Null,
  'Yakiniku' : IDL.Null,
  'Steakhouse' : IDL.Null,
  'Japanese' : IDL.Null,
  'Chinese' : IDL.Null,
  'Mexican' : IDL.Null,
  'Italian' : IDL.Null,
  'Fusion' : IDL.Null,
  'Kaiseki' : IDL.Null,
  'Vegan' : IDL.Null,
  'French' : IDL.Null,
  'Casual' : IDL.Null,
});
export const Restaurant = IDL.Record({
  'neighborhood' : Neighborhood,
  'mode' : Mode,
  'name' : IDL.Text,
  'priceRange' : IDL.Text,
  'details' : IDL.Text,
  'category' : Category,
  'rating' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getAllRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'getByCategory' : IDL.Func([Category], [IDL.Vec(Restaurant)], ['query']),
  'getByMode' : IDL.Func([Mode], [IDL.Vec(Restaurant)], ['query']),
  'getByName' : IDL.Func([IDL.Text], [IDL.Opt(Restaurant)], ['query']),
  'getByNeighborhood' : IDL.Func(
      [Neighborhood],
      [IDL.Vec(Restaurant)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Neighborhood = IDL.Variant({
    'Shinjuku' : IDL.Null,
    'Nihonbashi' : IDL.Null,
    'Ginza' : IDL.Null,
    'Aoyama' : IDL.Null,
    'TokyoStation' : IDL.Null,
    'Akasaka' : IDL.Null,
    'Asakusa' : IDL.Null,
    'Atago' : IDL.Null,
    'Shibuya' : IDL.Null,
    'Roppongi' : IDL.Null,
  });
  const Mode = IDL.Variant({ 'Date' : IDL.Null, 'Business' : IDL.Null });
  const Category = IDL.Variant({
    'Bar' : IDL.Null,
    'Sushi' : IDL.Null,
    'Yakiniku' : IDL.Null,
    'Steakhouse' : IDL.Null,
    'Japanese' : IDL.Null,
    'Chinese' : IDL.Null,
    'Mexican' : IDL.Null,
    'Italian' : IDL.Null,
    'Fusion' : IDL.Null,
    'Kaiseki' : IDL.Null,
    'Vegan' : IDL.Null,
    'French' : IDL.Null,
    'Casual' : IDL.Null,
  });
  const Restaurant = IDL.Record({
    'neighborhood' : Neighborhood,
    'mode' : Mode,
    'name' : IDL.Text,
    'priceRange' : IDL.Text,
    'details' : IDL.Text,
    'category' : Category,
    'rating' : IDL.Float64,
  });
  
  return IDL.Service({
    'getAllRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'getByCategory' : IDL.Func([Category], [IDL.Vec(Restaurant)], ['query']),
    'getByMode' : IDL.Func([Mode], [IDL.Vec(Restaurant)], ['query']),
    'getByName' : IDL.Func([IDL.Text], [IDL.Opt(Restaurant)], ['query']),
    'getByNeighborhood' : IDL.Func(
        [Neighborhood],
        [IDL.Vec(Restaurant)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };