/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'Bar' : null } |
  { 'Sushi' : null } |
  { 'Yakiniku' : null } |
  { 'Steakhouse' : null } |
  { 'Japanese' : null } |
  { 'Chinese' : null } |
  { 'Mexican' : null } |
  { 'Italian' : null } |
  { 'Fusion' : null } |
  { 'Kaiseki' : null } |
  { 'Vegan' : null } |
  { 'French' : null } |
  { 'Casual' : null };
export type Mode = { 'Date' : null } |
  { 'Business' : null };
export type Neighborhood = { 'Shinjuku' : null } |
  { 'Nihonbashi' : null } |
  { 'Ginza' : null } |
  { 'Aoyama' : null } |
  { 'TokyoStation' : null } |
  { 'Akasaka' : null } |
  { 'Asakusa' : null } |
  { 'Atago' : null } |
  { 'Shibuya' : null } |
  { 'Roppongi' : null };
export interface Restaurant {
  'neighborhood' : Neighborhood,
  'mode' : Mode,
  'name' : string,
  'priceRange' : string,
  'details' : string,
  'category' : Category,
  'rating' : number,
}
export interface _SERVICE {
  'getAllRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'getByCategory' : ActorMethod<[Category], Array<Restaurant>>,
  'getByMode' : ActorMethod<[Mode], Array<Restaurant>>,
  'getByName' : ActorMethod<[string], [] | [Restaurant]>,
  'getByNeighborhood' : ActorMethod<[Neighborhood], Array<Restaurant>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];