/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Restaurant {
    neighborhood: Neighborhood;
    mode: Mode;
    name: string;
    priceRange: string;
    details: string;
    category: Category;
    rating: number;
}
export enum Category {
    Bar = "Bar",
    Sushi = "Sushi",
    Yakiniku = "Yakiniku",
    Steakhouse = "Steakhouse",
    Japanese = "Japanese",
    Chinese = "Chinese",
    Mexican = "Mexican",
    Italian = "Italian",
    Fusion = "Fusion",
    Kaiseki = "Kaiseki",
    Vegan = "Vegan",
    French = "French",
    Casual = "Casual"
}
export enum Mode {
    Date_ = "Date",
    Business = "Business"
}
export enum Neighborhood {
    Shinjuku = "Shinjuku",
    Nihonbashi = "Nihonbashi",
    Ginza = "Ginza",
    Aoyama = "Aoyama",
    TokyoStation = "TokyoStation",
    Akasaka = "Akasaka",
    Asakusa = "Asakusa",
    Atago = "Atago",
    Shibuya = "Shibuya",
    Roppongi = "Roppongi"
}
export interface backendInterface {
    getAllRestaurants(): Promise<Array<Restaurant>>;
    getByCategory(category: Category): Promise<Array<Restaurant>>;
    getByMode(mode: Mode): Promise<Array<Restaurant>>;
    getByName(name: string): Promise<Restaurant | null>;
    getByNeighborhood(neighborhood: Neighborhood): Promise<Array<Restaurant>>;
}
import type { Category as _Category, Mode as _Mode, Neighborhood as _Neighborhood, Restaurant as _Restaurant } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllRestaurants(): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRestaurants();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRestaurants();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getByCategory(arg0: Category): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getByCategory(to_candid_Category_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getByCategory(to_candid_Category_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getByMode(arg0: Mode): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getByMode(to_candid_Mode_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getByMode(to_candid_Mode_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getByName(arg0: string): Promise<Restaurant | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getByName(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getByName(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getByNeighborhood(arg0: Neighborhood): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getByNeighborhood(to_candid_Neighborhood_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getByNeighborhood(to_candid_Neighborhood_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Mode_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mode): Mode {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Neighborhood_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Neighborhood): Neighborhood {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Restaurant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Restaurant): Restaurant {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Restaurant]): Restaurant | null {
    return value.length === 0 ? null : from_candid_Restaurant_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    neighborhood: _Neighborhood;
    mode: _Mode;
    name: string;
    priceRange: string;
    details: string;
    category: _Category;
    rating: number;
}): {
    neighborhood: Neighborhood;
    mode: Mode;
    name: string;
    priceRange: string;
    details: string;
    category: Category;
    rating: number;
} {
    return {
        neighborhood: from_candid_Neighborhood_n4(_uploadFile, _downloadFile, value.neighborhood),
        mode: from_candid_Mode_n6(_uploadFile, _downloadFile, value.mode),
        name: value.name,
        priceRange: value.priceRange,
        details: value.details,
        category: from_candid_Category_n8(_uploadFile, _downloadFile, value.category),
        rating: value.rating
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Shinjuku: null;
} | {
    Nihonbashi: null;
} | {
    Ginza: null;
} | {
    Aoyama: null;
} | {
    TokyoStation: null;
} | {
    Akasaka: null;
} | {
    Asakusa: null;
} | {
    Atago: null;
} | {
    Shibuya: null;
} | {
    Roppongi: null;
}): Neighborhood {
    return "Shinjuku" in value ? Neighborhood.Shinjuku : "Nihonbashi" in value ? Neighborhood.Nihonbashi : "Ginza" in value ? Neighborhood.Ginza : "Aoyama" in value ? Neighborhood.Aoyama : "TokyoStation" in value ? Neighborhood.TokyoStation : "Akasaka" in value ? Neighborhood.Akasaka : "Asakusa" in value ? Neighborhood.Asakusa : "Atago" in value ? Neighborhood.Atago : "Shibuya" in value ? Neighborhood.Shibuya : "Roppongi" in value ? Neighborhood.Roppongi : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Date: null;
} | {
    Business: null;
}): Mode {
    return "Date" in value ? Mode.Date : "Business" in value ? Mode.Business : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Bar: null;
} | {
    Sushi: null;
} | {
    Yakiniku: null;
} | {
    Steakhouse: null;
} | {
    Japanese: null;
} | {
    Chinese: null;
} | {
    Mexican: null;
} | {
    Italian: null;
} | {
    Fusion: null;
} | {
    Kaiseki: null;
} | {
    Vegan: null;
} | {
    French: null;
} | {
    Casual: null;
}): Category {
    return "Bar" in value ? Category.Bar : "Sushi" in value ? Category.Sushi : "Yakiniku" in value ? Category.Yakiniku : "Steakhouse" in value ? Category.Steakhouse : "Japanese" in value ? Category.Japanese : "Chinese" in value ? Category.Chinese : "Mexican" in value ? Category.Mexican : "Italian" in value ? Category.Italian : "Fusion" in value ? Category.Fusion : "Kaiseki" in value ? Category.Kaiseki : "Vegan" in value ? Category.Vegan : "French" in value ? Category.French : "Casual" in value ? Category.Casual : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Restaurant>): Array<Restaurant> {
    return value.map((x)=>from_candid_Restaurant_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Mode_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mode): _Mode {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Neighborhood_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Neighborhood): _Neighborhood {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    Bar: null;
} | {
    Sushi: null;
} | {
    Yakiniku: null;
} | {
    Steakhouse: null;
} | {
    Japanese: null;
} | {
    Chinese: null;
} | {
    Mexican: null;
} | {
    Italian: null;
} | {
    Fusion: null;
} | {
    Kaiseki: null;
} | {
    Vegan: null;
} | {
    French: null;
} | {
    Casual: null;
} {
    return value == Category.Bar ? {
        Bar: null
    } : value == Category.Sushi ? {
        Sushi: null
    } : value == Category.Yakiniku ? {
        Yakiniku: null
    } : value == Category.Steakhouse ? {
        Steakhouse: null
    } : value == Category.Japanese ? {
        Japanese: null
    } : value == Category.Chinese ? {
        Chinese: null
    } : value == Category.Mexican ? {
        Mexican: null
    } : value == Category.Italian ? {
        Italian: null
    } : value == Category.Fusion ? {
        Fusion: null
    } : value == Category.Kaiseki ? {
        Kaiseki: null
    } : value == Category.Vegan ? {
        Vegan: null
    } : value == Category.French ? {
        French: null
    } : value == Category.Casual ? {
        Casual: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mode): {
    Date: null;
} | {
    Business: null;
} {
    return value == Mode.Date ? {
        Date_: null
    } : value == Mode.Business ? {
        Business: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Neighborhood): {
    Shinjuku: null;
} | {
    Nihonbashi: null;
} | {
    Ginza: null;
} | {
    Aoyama: null;
} | {
    TokyoStation: null;
} | {
    Akasaka: null;
} | {
    Asakusa: null;
} | {
    Atago: null;
} | {
    Shibuya: null;
} | {
    Roppongi: null;
} {
    return value == Neighborhood.Shinjuku ? {
        Shinjuku: null
    } : value == Neighborhood.Nihonbashi ? {
        Nihonbashi: null
    } : value == Neighborhood.Ginza ? {
        Ginza: null
    } : value == Neighborhood.Aoyama ? {
        Aoyama: null
    } : value == Neighborhood.TokyoStation ? {
        TokyoStation: null
    } : value == Neighborhood.Akasaka ? {
        Akasaka: null
    } : value == Neighborhood.Asakusa ? {
        Asakusa: null
    } : value == Neighborhood.Atago ? {
        Atago: null
    } : value == Neighborhood.Shibuya ? {
        Shibuya: null
    } : value == Neighborhood.Roppongi ? {
        Roppongi: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
